<?xml version="1.0"?>
<package format="3">
  <name>tiago_wbc</name>
  <version>1.0.43</version>
  <description>The tiago_wbc package</description>

  <maintainer email="adria.roig@pal-robotics.com">Adrià Roig</maintainer>
  <maintainer email="sai.kishor@pal-robotics.com">Sai Kishor</maintainer>

  <license>Proprietary</license>

  <buildtool_depend>ament_cmake_auto</buildtool_depend>

  <exec_depend>pal_wbc_controller</exec_depend>
  <exec_depend>wbc_tasks</exec_depend>
  <exec_depend>pal_references</exec_depend>
  <exec_depend>capsule_collision</exec_depend>

  <test_depend>ament_lint_auto</test_depend>
  <test_depend>ament_lint_common</test_depend>

  <export>
    <build_type>ament_cmake</build_type>
  </export>
</package>

