whole_body_kinematic_controller:
  type: pal_wbc/WholeBodyControlKinematicController

  useFT: False  
  useIMU: False
  dt: 0.005
  floating_base: FixedBase
  formulation: velocity
  stack_configuration: tiago_admitance_stack
  solver_type: QpReductionuEqualitiesQuadprogHeapAllocation
  real_hardware: False
  
  robot_model_chains:
    [wrist_ft_link,
     xtion_optical_frame,
     laptop_tray_fixed_link]

  force_torque:
    wrist_ft:
      frame: wrist_ft_link

  default_configuration:

    # arm_1_joint: 1.7
    # arm_2_joint: -0.5
    # arm_3_joint: -3.4
    # arm_4_joint: 0.5
    # arm_5_joint: 3.4
    # arm_6_joint: 0.0
    # arm_7_joint: 0.0
    # head_1_joint: 0.0
    # head_2_joint: 0.0
    # torso_lift_joint: 0.14
    arm_1_joint: 0.11
    arm_2_joint: -0.51
    arm_3_joint: -3.22
    arm_4_joint: 2.0
    arm_5_joint: 1.91
    arm_6_joint: 0.36
    arm_7_joint: 1.08
    head_1_joint: 0.0
    head_2_joint: 0.0
    torso_lift_joint: 0.3


  go_to_admitance_arm_tool_link_RollPitchYaw:
    proportional_orientation_e_gain: 2.0
    torque_admitance_scaling: 2.6
    ft_smoothing_factor: 0.03
    use_smoothed_FT: True

  go_to_admitance_arm_tool_link_XYZ:
    proportional_position_e_gain: 2.5
    force_admitance_scaling: 0.02
    ft_smoothing_factor: 0.01
    use_smoothed_FT: True

  gaze_xtion_optical_frame:
    proportional_position_e_gain: 4.0

  position_joints:        
    - arm_1_joint
    - arm_2_joint
    - arm_3_joint
    - arm_4_joint
    - arm_5_joint
    - arm_6_joint
    - arm_7_joint
    - head_1_joint
    - head_2_joint
    - torso_lift_joint
    
  estimator_type: none
