whole_body_kinematic_controller:
  type: pal_wbc/WholeBodyControlKinematicController

  useFT: False
  useIMU: False
  dt: 0.005
  floating_base: FixedBase
  formulation: velocity
  stack_configuration: tiago_dynamic_ref_torso_head_stack
  solver_type: QpReductionuEqualitiesQuadprogHeapAllocation
  real_hardware: False
  
  robot_model_chains:
    [arm_tool_link,
     xtion_optical_frame,
     laptop_tray_fixed_link]

  default_configuration:
 
    # arm_1_joint: 1.7
    # arm_2_joint: -0.5
    # arm_3_joint: -3.4
    # arm_4_joint: 0.5
    # arm_5_joint: 3.4
    # arm_6_joint: 0.0
    # arm_7_joint: 0.0
    # head_1_joint: 0.0
    # head_2_joint: 0.0
    # torso_lift_joint: 0.14
    arm_1_joint: 1.0
    arm_2_joint: 0.7
    arm_3_joint: -0.5
    arm_4_joint: 1.72
    arm_5_joint: 0.93
    arm_6_joint: -0.69
    arm_7_joint: 0.2
    head_1_joint: 0.0
    head_2_joint: 0.0
    torso_lift_joint: 0.3

  go_to_arm_tool_link_RollPitchYaw:
    proportional_orientation_e_gain: 3.0

  go_to_arm_tool_link_XYZ:
    proportional_position_e_gain: 4.0

  gaze_xtion_optical_frame:
    proportional_position_e_gain: 4.0

  position_joints:        
    - arm_1_joint
    - arm_2_joint
    - arm_3_joint
    - arm_4_joint
    - arm_5_joint
    - arm_6_joint
    - arm_7_joint
    - head_1_joint
    - head_2_joint
    - torso_lift_joint
    
  estimator_type: none
