whole_body_kinematic_controller:
  type: pal_wbc/WholeBodyControlKinematicController
  
  useFT: False
  useIMU: False
  dt: 0.005
  floating_base: FixedBase
  formulation: velocity
  stack_configuration: tiago_stack
  solver_type: QpReductionuEqualitiesQuadprogHeapAllocation
  
  robot_model_chains:
    [hand_palm_link,
     xtion_optical_frame]

  default_configuration:
    arm_1_joint: 0.11
    arm_2_joint: -0.51
    arm_3_joint: -3.22
    arm_4_joint: 2.0
    arm_5_joint: 1.91
    arm_6_joint: 0.36
    arm_7_joint: 1.08
    head_1_joint: 0.0
    head_2_joint: 0.0
    torso_lift_joint: 0.3

  go_to_arm_7_link_RollPitchYaw:
    proportional_orientation_e_gain: 3.0

  go_to_arm_7_link_XYZ:
    proportional_position_e_gain: 4.0
    
  estimator_type: none
