whole_body_kinematic_controler:
  type: pal_wbc/WholeBodyControlKinematicController

  useFT: False  
  useIMU: False
  dt: 0.005
  floating_base: FixedBase
  formulation: velocity
  force_torque: True
  stack_configuration: tiago_rcp_stack
  solver: QpReductionuEqualitiesQuadprogHeapAllocation
  
  robot_model_chains:
    [arm_tool_link,
     xtion_optical_frame,
     laptop_tray_fixed_link]

  default_configuration:
 
    # arm_1_joint: 1.7
    # arm_2_joint: -0.5
    # arm_3_joint: -3.4
    # arm_4_joint: 0.5
    # arm_5_joint: 3.4
    # arm_6_joint: 0.0
    # arm_7_joint: 0.0
    # head_1_joint: 0.0
    # head_2_joint: 0.0
    # torso_lift_joint: 0.14
    arm_1_joint: 0.11
    arm_2_joint: -0.51
    arm_3_joint: -3.22
    arm_4_joint: 2.0
    arm_5_joint: 1.91
    arm_6_joint: 0.36
    arm_7_joint: 1.08
    head_1_joint: 0.0
    head_2_joint: 0.0
    torso_lift_joint: 0.3


  go_to_arm_tool_link_RollPitchYaw:
    proportional_orientation_e_gain: 3.0

  go_to_arm_tool_link_XYZ:
    proportional_position_e_gain: 4.0

  gaze_xtion_optical_frame:
    proportional_position_e_gain: 4.0
    
