whole_body_kinematic_controller:
  type: pal_wbc/WholeBodyControlKinematicController
  
  dt: 0.005
  floating_base: FixedBase
  formulation: velocity
  stack_configuration: tiago_fixed_base_stack
  solver_type: QpReductionuEqualitiesQuadprogHeapAllocation
  
  robot_model_chains:
    [arm_tool_link,
     xtion_rgb_optical_frame,
     xtion_optical_frame]

  default_configuration:
    arm_1_joint: 0.11
    arm_2_joint: -0.51
    arm_3_joint: -3.22
    arm_4_joint: 2.0
    arm_5_joint: 1.91
    arm_6_joint: 0.36
    arm_7_joint: 1.08
    head_1_joint: 0.0 
    head_2_joint: 0.0
    torso_lift_joint: 0.3

  initialize_bfp_tf: false
  use_home_posture: true
  use_odom: false
