pal_wbc_controller:
  ros__parameters:
    type: "pal_wbc/WBCController"
    command_joints: ["arm_1_joint", "arm_2_joint", "arm_3_joint", "arm_4_joint", "arm_5_joint", "arm_6_joint", "arm_7_joint", "torso_lift_joint", "head_1_joint", "head_2_joint"]
    command_interface: "position"
    robot_description: ""
    root_link: "base_link"
    tip_links: ["arm_tool_link", "head_front_camera_optical_frame"]
    controller_dt: 0.01
    use_home_posture: true
    formulation: "velocity"
    wbc_model_type: "rbdl"
    floating_base_type: "FIXED"
    solver_type: "QpReductionuEqualitiesQuadprogHeapAllocation"
    stack_from_yaml: true
    package_name: "tiago_wbc"
    stack_configuration: "/config/default_kinematic_stack.yaml"
    use_odom: false
    initialize_bfp_tf: false
    openloop: true
    foot_length: 0.0
    foot_width: 0.0
    mu: 0.0

    wbc_controller_pid:
      arm_1_joint:
        p: 1.
        i: 0.
        d: 0.2
      arm_2_joint:
        p: 1.
        i: 0.
        d: 0.2
      arm_3_joint:
        p: 1.
        i: 0.
        d: 0.2
      arm_4_joint:
        p: 1.
        i: 0.
        d: 0.2
      arm_5_joint:
        p: 1.
        i: 0.
        d: 0.2
      arm_6_joint:
        p: 1.
        i: 0.
        d: 0.2
      arm_7_joint:
        p: 1.
        i: 0.
        d: 0.2
      torso_lift_joint:
        p: 1.
        i: 0.
        d: 0.2

    home_posture:
      arm_1_joint:
        position: 0.11
      arm_2_joint:
        position: -0.51
      arm_3_joint:
        position: -3.22
      arm_4_joint:
        position: 2.0
      arm_5_joint:
        position: 1.91
      arm_6_joint:
        position: 0.36
      arm_7_joint:
        position: 1.08
      torso_lift_joint:
        position: 0.3
      head_1_joint:
        position: 0.0
      head_2_joint:
        position: 0.0
