cartesian_orientation:  # Control end-effector orientation
  type: "pal_wbc/GoToKinematicTask"
  weight: 1.0
  priority: 3
  start: true
  damping: 0.1
  link_name: "arm_tool_link" # Controlled link
  reference_type: "pal_references::TopicPoseReference" #Follows geometry_msgs::msg::Pose In this case, it would be named /arm_tool_link_pose
  pid_orientation_gains:  # PID parameters for orientation control
    k_p: 2.0
    k_d: 0.0
    k_i: 0.0
    i_min: 0.0
    i_max: 0.0
    antiwindup: false
    damping_ratio: 1.0
    critically_damped: false
  offset_orientation:
    x: 0.0
    y: 0.0
    z: 0.0
    w: 1.0  # No additional rotation
  coordinates: [Roll, Pitch, Yaw]  # Controls orientation in Euler angles